services:
  mysqldatabase: 
    image: "mysql:8.0.39"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./server/Saily/Database:/home
    ports: 
      - "3306:3306"
    networks:
      - node-to-database-network

  mynodeserver:
    image: "node:20.12.2"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/Saily/ServerApi:/home/node/app
    ports: 
      - "8567:8567"
    command: "npm start"
    depends_on:
      - mysqldatabase
    networks:
      - node-to-database-network
    links:
      - mysqldatabase:databasehostname
    
networks:
  node-to-database-network: