-- MySQL Script generated by MySQL Workbench
-- Wed 16 Oct 2024 03:56:03 PM CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema huracanp_login_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `huracanp_login_databasev2` ;

-- -----------------------------------------------------
-- Schema huracanp_login_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `huracanp_login_databasev2` ;
USE `huracanp_login_databasev2` ;

-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`user_account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`user_account` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`user_account` (
  `user_id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(500) NOT NULL,
  `password_hash` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_email_UNIQUE` (`user_email` ASC) VISIBLE)
ENGINE = InnoDB;

--
-- Dumping data for table `user_account`
--

INSERT INTO `user_account` (`user_email`, `password_hash`) VALUES
('zero', '$2a$10$1mwuFEn94P3NlfmtSQL/cec00cm6Tn7hJLItSoH6/gT3FzxDV.qiG'),
('g.rasera@huracanmarine.com', '$2a$10$ii4b6pmQXygk35vcpkF9Qe5BzSKQd5lcd8dLXt.zsKoQX2FUOZsF6'),
('g.sossai@huracanmarine.com', '$2a$10$ii4b6pmQXygk35vcpkF9Qe5BzSKQd5lcd8dLXt.zsKoQX2FUOZsF6'),
('l.scomazzon@huracanmarine.com', '$2a$10$ii4b6pmQXygk35vcpkF9Qe5BzSKQd5lcd8dLXt.zsKoQX2FUOZsF6'),
('b.ghizzo@huracanmarine.com', '$2a$10$ii4b6pmQXygk35vcpkF9Qe5BzSKQd5lcd8dLXt.zsKoQX2FUOZsF6'),
('f.moro@huracanmarine.com', '$2a$10$ii4b6pmQXygk35vcpkF9Qe5BzSKQd5lcd8dLXt.zsKoQX2FUOZsF6');
COMMIT;



-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`boats`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`boats` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`boats` (
  `boat_id` VARCHAR(20) NOT NULL,
  `mqtt_user` VARCHAR(10) NULL,
  `mqtt_password` VARCHAR(100) NULL,
  `user_id` BIGINT(20) UNSIGNED NULL,
  PRIMARY KEY (`boat_id`),
  UNIQUE INDEX `boat_id_UNIQUE` (`boat_id` ASC) VISIBLE,
  INDEX `fk_boats_user_account1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_boats_user_account1`
    FOREIGN KEY (`user_id`)
    REFERENCES `huracanp_login_databasev2`.`user_account` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

--
-- Dumping data for table `boats`
--

INSERT INTO `boats` (`boat_id`, `mqtt_user`, `mqtt_password`) VALUES
('qwertyuiop', 'test', 'test'),
('0x0001', 'test', 'test'),
('0x0002', 'test', 'test'),
('0x0003', 'test', 'test'),
('0x0004', 'test', 'test'),
('0x0005', 'test', 'test'),
('0x0006', 'test', 'test'),
('0x0007', 'test', 'test'),
('0x0008', 'test', 'test');


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`high_power_battery_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`high_power_battery_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`high_power_battery_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats1`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`actuator_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`actuator_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`actuator_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats10`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`electric_motor_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`electric_motor_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`electric_motor_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats11`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`endothermic_motor_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`endothermic_motor_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`endothermic_motor_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats12`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`general_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`general_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`general_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats100`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`nmea2000_vtg_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`nmea2000_vtg_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`nmea2000_vtg_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats1000`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `huracanp_login_databasev2`.`vehicle_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `huracanp_login_databasev2`.`vehicle_info` ;

CREATE TABLE IF NOT EXISTS `huracanp_login_databasev2`.`vehicle_info` (
  `json_value` VARCHAR(2000) NOT NULL,
  `timestamp` VARCHAR(45) NOT NULL,
  `boats_boat_id` VARCHAR(20) NOT NULL,
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  INDEX `fk_high_power_battery_info_boats1_idx` (`boats_boat_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_high_power_battery_info_boats1001`
    FOREIGN KEY (`boats_boat_id`)
    REFERENCES `huracanp_login_databasev2`.`boats` (`boat_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Data
INSERT INTO `huracanp_login_databasev2`.`nmea2000_vtg_info`
  (`json_value`, `timestamp`, `boats_boat_id`,`id`)
VALUES
  ('{"satellitesCount":0,"isFixed":false,"SOG":0.0,"lat":45.432453,"lng":12.328085}', now(), "0x0001", null),
  ('{"satellitesCount":0,"isFixed":false,"SOG":0.0,"lat":45.441003,"lng":12.309873}', now(), "0x0002", null),
  ('{"satellitesCount":0,"isFixed":false,"SOG":0.0,"lat":45.458972,"lng":12.380915}', now(), "0x0003", null);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
