name: saily
description: "Welcome to Saily"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_map: ^7.0.2
  flutter_map_cancellable_tile_provider: ^3.0.0
  xml: ^6.5.0
  flutter_settings_screens: ^0.3.4
  shared_preferences: ^2.2.3
  cupertino_battery_indicator: ^1.1.0
  # this is importantant for camera usage on android
  camera: ^0.10.0+2
  share: ^2.0.4
  syncfusion_flutter_gauges: ^26.2.14
  animated_battery_gauge: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - images/boat.jpeg
    - images/map.png
    - images/water.png
    - images/dashboard.png
    - images/huracan.png

    - sharable/cannes.gpx

  