name: flutter_keycloak_example
description: Demonstrates how to use FlutterKeycloak

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_keycloak:
    path: ../
  get_storage: ^2.0.0

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true