name: flutter_keycloak
description: A Flutter Keycloak wrapper, to manage the authentication and tokens automatically
version: 1.1.5
homepage: https://github.com/TheFe91/flutter_keycloak

environment:
  sdk: '^3.5.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  get_storage: ^2.0.0
  http: ^1.2.2

dev_dependencies:
  flutter_lints: ^2.0.1

flutter: